# Generated by Django 5.2.5 on 2025-08-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('program', models.CharField(blank=True, max_length=120)),
                ('university', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('profile_url', models.URLField(blank=True, help_text='Optional: LinkedIn/Personal site')),
                ('photo_url', models.URLField(blank=True, help_text='Temporary: external image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
